In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('/content/data[1].csv')

In [ ]:
data.head(2)

ID  ACCESS_ALL_DOWNLOADS  ACCESS_CACHE_FILESYSTEM  \
0  2000                   0.0                      0.0   
1  2001                   0.0                      0.0   

   ACCESS_CHECKIN_PROPERTIES  ACCESS_COARSE_LOCATION  ACCESS_COARSE_UPDATES  \
0                        0.0                     0.0                    0.0   
1                        0.0                     0.0                    0.0   

   ACCESS_FINE_LOCATION  ACCESS_LOCATION_EXTRA_COMMANDS  ACCESS_MOCK_LOCATION  \
0                   0.0                             0.0                   0.0   
1                   0.0                             0.0                   0.0   

   ACCESS_MTK_MMHW  ...  Landroid/telephony/TelephonyManager;->getLine1Number  \
0              0.0  ...                                                1.0      
1              0.0  ...                                                0.0      

   Landroid/telephony/TelephonyManager;->getNetworkOperator  \
0                                                1.0          
1                                                0.0          

   Landroid/telephony/TelephonyManager;->getNetworkOperatorName  \
0                                                1.0              
1                                                0.0              

   Landroid/telephony/TelephonyManager;->getNetworkCountryIso  \
0                                                0.0            
1                                                1.0            

   Landroid/telephony/TelephonyManager;->getSimOperator  \
0                                                0.0      
1                                                0.0      

   Landroid/telephony/TelephonyManager;->getSimOperatorName  \
0                                                0.0          
1                                                0.0          

   Landroid/telephony/TelephonyManager;->getSimCountryIso  \
0                                                0.0        
1                                                1.0        

   Landroid/telephony/TelephonyManager;->getSimSerialNumber  \
0                                                0.0          
1                                                0.0          

   Lorg/apache/http/impl/client/DefaultHttpClient;->execute  Label  
0                                                1.0           1.0  
1                                                0.0           1.0  

[2 rows x 243 columns]

In [ ]:
cols = data.columns
pd.set_option('display.max_columns', None)
print(cols)

Index(['ID', 'ACCESS_ALL_DOWNLOADS', 'ACCESS_CACHE_FILESYSTEM',
       'ACCESS_CHECKIN_PROPERTIES', 'ACCESS_COARSE_LOCATION',
       'ACCESS_COARSE_UPDATES', 'ACCESS_FINE_LOCATION',
       'ACCESS_LOCATION_EXTRA_COMMANDS', 'ACCESS_MOCK_LOCATION',
       'ACCESS_MTK_MMHW',
       ...
       'Landroid/telephony/TelephonyManager;->getLine1Number',
       'Landroid/telephony/TelephonyManager;->getNetworkOperator',
       'Landroid/telephony/TelephonyManager;->getNetworkOperatorName',
       'Landroid/telephony/TelephonyManager;->getNetworkCountryIso',
       'Landroid/telephony/TelephonyManager;->getSimOperator',
       'Landroid/telephony/TelephonyManager;->getSimOperatorName',
       'Landroid/telephony/TelephonyManager;->getSimCountryIso',
       'Landroid/telephony/TelephonyManager;->getSimSerialNumber',
       'Lorg/apache/http/impl/client/DefaultHttpClient;->execute', 'Label'],
      dtype='object', length=243)


In [ ]:
data.shape

(4465, 243)

In [ ]:
def replace_null_with_mean(data):
    return data.dropna()
data=replace_null_with_mean(data)

In [ ]:
missing=data.isnull().sum()/data.shape[0]*100
pd.set_option('display.max_rows', None)
print(missing)

ID                                                                   0.0
ACCESS_ALL_DOWNLOADS                                                 0.0
ACCESS_CACHE_FILESYSTEM                                              0.0
ACCESS_CHECKIN_PROPERTIES                                            0.0
ACCESS_COARSE_LOCATION                                               0.0
ACCESS_COARSE_UPDATES                                                0.0
ACCESS_FINE_LOCATION                                                 0.0
ACCESS_LOCATION_EXTRA_COMMANDS                                       0.0
ACCESS_MOCK_LOCATION                                                 0.0
ACCESS_MTK_MMHW                                                      0.0
ACCESS_NETWORK_STATE                                                 0.0
ACCESS_PROVIDER                                                      0.0
ACCESS_SERVICE                                                       0.0
ACCESS_SHARED_DATA                                 

In [ ]:
data.dtypes

ID                                                                     int64
ACCESS_ALL_DOWNLOADS                                                 float64
ACCESS_CACHE_FILESYSTEM                                              float64
ACCESS_CHECKIN_PROPERTIES                                            float64
ACCESS_COARSE_LOCATION                                               float64
ACCESS_COARSE_UPDATES                                                float64
ACCESS_FINE_LOCATION                                                 float64
ACCESS_LOCATION_EXTRA_COMMANDS                                       float64
ACCESS_MOCK_LOCATION                                                 float64
ACCESS_MTK_MMHW                                                      float64
ACCESS_NETWORK_STATE                                                 float64
ACCESS_PROVIDER                                                      float64
ACCESS_SERVICE                                                       float64

In [ ]:
data['Label'].value_counts()

1.0    3565
0.0     899
Name: Label, dtype: int64

In [ ]:
x=data.drop(columns=['ID','Label'])
y=data['Label']

In [ ]:
x.shape

(4464, 241)

In [ ]:
y.shape

(4464,)

In [ ]:
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE

oversample = SMOTE()
x, y = oversample.fit_resample(x, y)

In [ ]:
x.shape

(7130, 241)

In [ ]:
y.value_counts()

1.0    3565
0.0    3565
Name: Label, dtype: int64

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import xgboost as xgb

In [ ]:
def create_and_validate_classification_models(X, y):
    models = {
        'Logistic Regression': LogisticRegression(),
        'K-Nearest Neighbors': KNeighborsClassifier(),
        'Decision Tree': DecisionTreeClassifier(),
        'Random Forest': RandomForestClassifier(),
        'Support Vector Machine': SVC(),
        'Xg Boost':xgb.XGBClassifier()
    }
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    results = {}
    for model_name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        class_report = classification_report(y_test, y_pred)
        conf_matrix = confusion_matrix(y_test, y_pred)
        results[model_name] = {
            'model': model,
            'accuracy': accuracy,
            'classification_report': class_report,
            'confusion_matrix': conf_matrix
        }
        print(f"Model: {model_name}")
        print(f"Accuracy: {accuracy:.7f}")
        print("Classification Report:")
        print(class_report)
        print("Confusion Matrix:")
        print(conf_matrix)
        print("----------------------------")
    return results

In [ ]:
print("Normal Data")
print()
create_and_validate_classification_models(x,y)

Normal Data

Model: Logistic Regression
Accuracy: 0.9908836
Classification Report:
              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99       694
         1.0       0.99      0.99      0.99       732

    accuracy                           0.99      1426
   macro avg       0.99      0.99      0.99      1426
weighted avg       0.99      0.99      0.99      1426

Confusion Matrix:
[[690   4]
 [  9 723]]
----------------------------
Model: K-Nearest Neighbors
Accuracy: 0.9950912
Classification Report:
              precision    recall  f1-score   support

         0.0       0.99      1.00      0.99       694
         1.0       1.00      0.99      1.00       732

    accuracy                           1.00      1426
   macro avg       1.00      1.00      1.00      1426
weighted avg       1.00      1.00      1.00      1426

Confusion Matrix:
[[692   2]
 [  5 727]]
----------------------------
Model: Decision Tree
Accuracy: 0.9936886
Classificati

{'Logistic Regression': {'model': LogisticRegression(),
  'accuracy': 0.9908835904628331,
  'classification_report': '              precision    recall  f1-score   support\n\n         0.0       0.99      0.99      0.99       694\n         1.0       0.99      0.99      0.99       732\n\n    accuracy                           0.99      1426\n   macro avg       0.99      0.99      0.99      1426\nweighted avg       0.99      0.99      0.99      1426\n',
  'confusion_matrix': array([[690,   4],
         [  9, 723]])},
 'K-Nearest Neighbors': {'model': KNeighborsClassifier(),
  'accuracy': 0.9950911640953717,
  'classification_report': '              precision    recall  f1-score   support\n\n         0.0       0.99      1.00      0.99       694\n         1.0       1.00      0.99      1.00       732\n\n    accuracy                           1.00      1426\n   macro avg       1.00      1.00      1.00      1426\nweighted avg       1.00      1.00      1.00      1426\n',
  'confusion_matrix': a

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [ ]:
forest=RandomForestClassifier()
forest.fit(x_train,y_train)

RandomForestClassifier()

Training test

In [ ]:
train_predict=forest.predict(x_train)
print(accuracy_score(y_train,train_predict))

0.9970196353436185


Testing

In [ ]:
test_predict=forest.predict(x_test)
print(accuracy_score(y_test,test_predict))

0.9971949509116409


In [ ]:
print(test_predict)

[0. 1. 1. ... 0. 1. 0.]


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

In [ ]:
def evaluate_classification_model(model, X, y, test_size):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=test_size,random_state=42)
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    accuracy=accuracy_score(y_test, y_pred)
    precision=precision_score(y_test, y_pred, average='weighted')
    recall=recall_score(y_test, y_pred, average='weighted')
    f1=f1_score(y_test, y_pred, average='weighted')
    conf_matrix=confusion_matrix(y_test, y_pred)

    print("Metrics for the Classification Model:")
    print(f"Accuracy: {accuracy:.6f}")
    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")
    print(f"F1-score: {f1:.2f}")
    print("Confusion Matrix:")
    print(conf_matrix)

In [ ]:
logistic=LogisticRegression()
knn=KNeighborsClassifier()
decision=DecisionTreeClassifier()

In [ ]:
evaluate_classification_model(forest,x,y,0.2)

Metrics for the Classification Model:
Accuracy: 0.997195
Precision: 1.00
Recall: 1.00
F1-score: 1.00
Confusion Matrix:
[[694   0]
 [  4 728]]


In [ ]:
logistic.fit(x_train,y_train)

LogisticRegression()

In [ ]:
test_logis_predict=logistic.predict(x_test)
print(accuracy_score(y_test,test_logis_predict))

0.9922861150070126


In [ ]:
xg=xgb.XGBClassifier()

In [ ]:
xg.fit(x_train,y_train)
test_xg_predict=xg.predict(x_test)
print(accuracy_score(y_test,test_xg_predict))

0.9922861150070126


In [ ]:
test=pd.read_csv('/content/test[1].csv')

In [ ]:
test.columns

Index(['ID', 'ACCESS_ALL_DOWNLOADS', 'ACCESS_CACHE_FILESYSTEM',
       'ACCESS_CHECKIN_PROPERTIES', 'ACCESS_COARSE_LOCATION',
       'ACCESS_COARSE_UPDATES', 'ACCESS_FINE_LOCATION',
       'ACCESS_LOCATION_EXTRA_COMMANDS', 'ACCESS_MOCK_LOCATION',
       'ACCESS_MTK_MMHW',
       ...
       'Landroid/content/pm/PackageManager;->getInstalledPackages',
       'Landroid/telephony/TelephonyManager;->getLine1Number',
       'Landroid/telephony/TelephonyManager;->getNetworkOperator',
       'Landroid/telephony/TelephonyManager;->getNetworkOperatorName',
       'Landroid/telephony/TelephonyManager;->getNetworkCountryIso',
       'Landroid/telephony/TelephonyManager;->getSimOperator',
       'Landroid/telephony/TelephonyManager;->getSimOperatorName',
       'Landroid/telephony/TelephonyManager;->getSimCountryIso',
       'Landroid/telephony/TelephonyManager;->getSimSerialNumber',
       'Lorg/apache/http/impl/client/DefaultHttpClient;->execute'],
      dtype='object', length=242)

In [ ]:
test.shape

(2964, 242)

In [ ]:
id=test['ID']
test=test.drop(columns=['ID'])

In [ ]:
test.isnull().sum()

ACCESS_ALL_DOWNLOADS                                                 1
ACCESS_CACHE_FILESYSTEM                                              1
ACCESS_CHECKIN_PROPERTIES                                            1
ACCESS_COARSE_LOCATION                                               1
ACCESS_COARSE_UPDATES                                                1
ACCESS_FINE_LOCATION                                                 1
ACCESS_LOCATION_EXTRA_COMMANDS                                       1
ACCESS_MOCK_LOCATION                                                 1
ACCESS_MTK_MMHW                                                      1
ACCESS_NETWORK_STATE                                                 1
ACCESS_PROVIDER                                                      1
ACCESS_SERVICE                                                       1
ACCESS_SHARED_DATA                                                   1
ACCESS_SUPERUSER                                                     1
ACCESS

In [ ]:
def replace_null_with(df):
    for column in df.columns:
        if df[column].dtype in ['int64', 'float64']:
            column_mean = df[column].mean()
            df[column].fillna(column_mean, inplace=True)
    return df

In [ ]:
test=replace_null_with(test)

In [ ]:
actual_prediction=forest.predict(test)

In [ ]:
actual_prediction.shape

(2964,)

In [ ]:
final_data= pd.DataFrame({'ID': id, 'Label': actual_prediction})

In [ ]:
final_data.head(2)

ID  Label
0  3501    1.0
1  3502    1.0

In [ ]:
final_data.columns

Index(['ID', 'Label'], dtype='object')

In [ ]:
final_data.shape

(2964, 2)

In [ ]:
final_data.to_csv('submission.csv', index=False)