In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score,mean_squared_error

In [3]:
data=pd.read_csv('accenture_salary.csv')

In [14]:
x=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values

In [15]:
y

array([  17000,   27000,   40000,   65000,  100000,  150000,  250000,
        400000,  650000, 1000000, 1800000, 4000000], dtype=int64)

In [16]:
y=y.reshape(len(y),1)
print(y)

[[  17000]
 [  27000]
 [  40000]
 [  65000]
 [ 100000]
 [ 150000]
 [ 250000]
 [ 400000]
 [ 650000]
 [1000000]
 [1800000]
 [4000000]]


In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler=StandardScaler()

In [20]:
x=scaler.fit_transform(x)
y=scaler.fit_transform(y)

In [21]:
from sklearn.svm import SVR

In [23]:
regressor=SVR(kernel='rbf')

In [24]:
regressor.fit(x,y)

C:\Users\SREERAM\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [25]:
predict=regressor.predict(x)

In [26]:
predict

array([-0.51997656, -0.53589004, -0.51446569, -0.48013351, -0.44569124,
       -0.40155912, -0.32132488, -0.17642825,  0.04789058,  0.33815237,
        0.89106499,  1.00649317])

In [27]:
y

array([[-0.62024154],
       [-0.61126879],
       [-0.59960421],
       [-0.57717233],
       [-0.54576769],
       [-0.50090393],
       [-0.4111764 ],
       [-0.27658511],
       [-0.05226629],
       [ 0.26178007],
       [ 0.9796003 ],
       [ 2.95360593]])

In [28]:
from matplotlib import pyplot as plt

In [ ]:
plt.scatter(x,predict,color='red')
plt.title('Comparision')
p