#N- Dimensional array
Numpy
Arrays allows you to perform mathematical operations on whole blocks of data.

In [2]:
!pip install numpy 
#used to install numpy
import numpy as np 
#used to import numpy 

In [3]:
scores = [89,56.34, 76,89, 98] #creating a list
array = np.array(scores) #this function is used to create an array
print(array)
print(array.dtype)  # .dtype return the data type of the elements inside an array

[89.   56.34 76.   89.   98.  ]
float64


In [4]:
# Nested lists with equal length, will be converted into a multidimensional array
scores_1 = [[34,56,23,89], [11,45,76,34]]
second_arr = np.array(scores_1)
print("The Array is: ",second_arr)
print("The Dimension is: ",second_arr.ndim)  #.ndim gives you the dimensions of an array.
print("The Shape of array is: ",second_arr.shape) #(number of rows, number of columns)
print(second_arr.dtype) 

The Array is:  [[34 56 23 89]
 [11 45 76 34]]
The Dimension is:  2
The Shape of array is:  (2, 4)
int32


In [5]:
x = np.zeros(10) # returns a array of zeros of the size mentioned , the same applies for np.ones(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((4,3)) # you can also mention the shape of the array (Multi Dimentional)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#This will create a NumPy array with values from 0 to the mentioned number (exclusive).
np.arange(15) #only till 14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.eye(6) # Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [9]:
#Batch operations on data can be performed without using for loops, this is called vectorization
#no need of for loops for basic arithmetic operations on arrays
scores = [89,56.34, 76,89, 98]
first_arr =np.array(scores)
print(first_arr)
print(first_arr * first_arr)
print(first_arr - first_arr)
print(1/(first_arr))
print(first_arr ** 0.5)

[89.   56.34 76.   89.   98.  ]
[7921.     3174.1956 5776.     7921.     9604.    ]
[0. 0. 0. 0. 0.]
[0.01123596 0.01774938 0.01315789 0.01123596 0.01020408]
[9.43398113 7.5059976  8.71779789 9.43398113 9.89949494]


#Indexing and Slicing

In [10]:
# you may want to select a subset of your data, for which Numpy array indexing is really useful
new_arr = np.arange(12)
print(new_arr)
print(new_arr[5])
print(new_arr[4:9])
new_arr[4:9] = 99 #assign sequence of values from 4 to 9 as 99
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
5
[4 5 6 7 8]
[ 0  1  2  3 99 99 99 99 99  9 10 11]


In [11]:
# A major diffence between lists and array is that, array slices are views on the original array. This means that
# the data is not copied, and any modifications to the view will be reflected in the source
#  array. 
modi_arr = new_arr[4:9] 
modi_arr[1] = 123456
print(new_arr)                  # you can see the changes are refelected in main array. 
modi_arr[:]                  # the sliced variable
            

[     0      1      2      3     99 123456     99     99     99      9
     10     11]


array([    99, 123456,     99,     99,     99])

In [12]:
# arrays can be treated like matrices
matrix_arr =np.array([[3,4,5],[6,7,8],[9,5,1]])
print(matrix_arr)
print(matrix_arr[1])
print(matrix_arr[0][2]) #first row and third column
print(matrix_arr[0,2]) # This is same as the above operation

[[3 4 5]
 [6 7 8]
 [9 5 1]]
[6 7 8]
5
5


In [14]:
# 3d arrays -> this is a 2x2x3 array
three_d_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(three_d_arr)
print(three_d_arr.shape)
print("returns the second list inside first list {}".format(three_d_arr[0,1]))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
returns the second list inside first list [4 5 6]


In [15]:
three_d_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(three_d_arr[0])
#if you omit later indices, the returned object will be a lowerdimensional
# ndarray consisting of all the data along the higher dimensions

[[1 2 3]
 [4 5 6]]


I have used [format](https://docs.python.org/2/tutorial/inputoutput.html) function in the below cell.

In [16]:
copied_values = three_d_arr[0].copy() # copy arr[0] value to copied_values
three_d_arr[0]= 99  # change all values of arr[0] to 99 
print("New value of three_d_arr: \n{}\n-------".format(three_d_arr)) # check the new value of three_d_arr 
three_d_arr[0] = copied_values # assign copied values back to three_d_arr[0]
print("three_d_arr again: \n{}".format(three_d_arr))

New value of three_d_arr: 
[[[99 99 99]
  [99 99 99]]

 [[ 7  8  9]
  [10 11 12]]]
-------
three_d_arr again: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
matrix_arr =np.array([[3,4,5],[6,7,8],[9,5,1]])
print("The original matrix {}:".format(matrix_arr))
print("slices the first two rows:{}".format(matrix_arr[:2])) # similar to list slicing. returns first two rows of the array
print("Slices the first two rows and two columns:{}".format(matrix_arr[:2, 1:]))
print("returns 6 and 7: {}".format(matrix_arr[1,:2]))
print("Returns first column: {}".format(matrix_arr[:,:1])) #Note that a colon by itself means to take the entire axis

The original matrix [[3 4 5]
 [6 7 8]
 [9 5 1]]:
slices the first two rows:[[3 4 5]
 [6 7 8]]
Slices the first two rows and two columns:[[4 5]
 [7 8]]
returns 6 and 7: [6 7]
Returns first column: [[3]
 [6]
 [9]]


In [19]:
personals = np.array(['Manu', 'Jeevan', 'Prakash', 'Manu', 'Prakash', 'Jeevan', 'Prakash'])
print(personals == 'Manu')#checks for the string 'Manu' in personals. If present it returns true; else false#

[ True False False  True False False False]


In [20]:
#Import random module from Numpy
from numpy import random 
random_no = random.randn(7,4)
print(random_no)
random_no[personals =='Manu'] #The function returns the rows for which the value of manu is true
# Check the image displayed in the cell below. 

[[-0.8902213   0.55081549  0.1325308   0.50049262]
 [-0.92844195  0.70685053 -0.81346507  0.12768338]
 [ 0.88823336 -0.80346119  1.35148041 -0.46497775]
 [-1.2803576  -1.70266722 -1.11285008 -0.64775129]
 [ 1.37626614 -0.90167158  0.26198734  0.97526928]
 [-0.5097623   0.3860929   0.12176822 -0.77184476]
 [ 1.71101074 -0.49604595 -0.25838715 -1.75812135]]


array([[-0.8902213 ,  0.55081549,  0.1325308 ,  0.50049262],
       [-1.2803576 , -1.70266722, -1.11285008, -0.64775129]])

In [22]:
random_no[personals == 'Manu', 2:] #First two columns and first two rows.

array([[ 0.1325308 ,  0.50049262],
       [-1.11285008, -0.64775129]])

In [24]:
# To select everything except 'Manu', you can != or negate the condition using -:
print(personals != 'Manu')
random_no[(personals != 'Manu')] #get everything except 1st and 4th rows

[False  True  True False  True  True  True]


array([[-0.92844195,  0.70685053, -0.81346507,  0.12768338],
       [ 0.88823336, -0.80346119,  1.35148041, -0.46497775],
       [ 1.37626614, -0.90167158,  0.26198734,  0.97526928],
       [-0.5097623 ,  0.3860929 ,  0.12176822, -0.77184476],
       [ 1.71101074, -0.49604595, -0.25838715, -1.75812135]])

In [25]:
# you can use boolean operator &(and), |(or)
new_variable = (personals == 'Manu') | (personals == 'Jeevan')
print(new_variable)
random_no[new_variable] 

[ True  True False  True False  True False]


array([[-0.8902213 ,  0.55081549,  0.1325308 ,  0.50049262],
       [-0.92844195,  0.70685053, -0.81346507,  0.12768338],
       [-1.2803576 , -1.70266722, -1.11285008, -0.64775129],
       [-0.5097623 ,  0.3860929 ,  0.12176822, -0.77184476]])

In [26]:
random_no[random_no < 0] =0 
random_no # This will set all negative values to zero

array([[0.        , 0.55081549, 0.1325308 , 0.50049262],
       [0.        , 0.70685053, 0.        , 0.12768338],
       [0.88823336, 0.        , 1.35148041, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [1.37626614, 0.        , 0.26198734, 0.97526928],
       [0.        , 0.3860929 , 0.12176822, 0.        ],
       [1.71101074, 0.        , 0.        , 0.        ]])

In [27]:
random_no[ personals != 'Manu'] = 9 # This will set all rows except 1 and 4 to 9. 
random_no

array([[0.        , 0.55081549, 0.1325308 , 0.50049262],
       [9.        , 9.        , 9.        , 9.        ],
       [9.        , 9.        , 9.        , 9.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [9.        , 9.        , 9.        , 9.        ],
       [9.        , 9.        , 9.        , 9.        ],
       [9.        , 9.        , 9.        , 9.        ]])

#Fancy Indexing(Indexing using integer arrays)
Fancy indexing copies data into a new array


In [28]:
algebra = random.randn(7,4) # empty will return a matrix of size 7,4
for j in range(7):
    algebra[j] = j
algebra

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [29]:
# To select a subset of rows in particular order, you can simply pass a list.
algebra[[4,5,1]] #returns a subset of rows

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [1., 1., 1., 1.]])

In [30]:
print(np.arange(20))
print(np.arange(20).reshape(5,4)) #differrence between regular array and a reshaped one

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [31]:
fancy = np.arange(36).reshape(9,4) #reshape is to reshape an array
print(fancy)
fancy[[1,3,5,7],[2,3,3,2]] #the position of the output array are[(1,2),(3,3),(5,3),(7,2)]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


array([ 6, 15, 23, 30])

In [32]:
fancy[[1, 4, 8, 2]][:, [0, 3, 1, 2]] # entire first row is selected, but the elements are interchanged, same goes for 4th, 8th and 2 nd row.

array([[ 4,  7,  5,  6],
       [16, 19, 17, 18],
       [32, 35, 33, 34],
       [ 8, 11,  9, 10]])

In [33]:
# another way to do the above operation is by using np.ix_ function.
fancy[np.ix_([1,4,8,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [16, 19, 17, 18],
       [32, 35, 33, 34],
       [ 8, 11,  9, 10]])

#Transposing Arrays

In [34]:
transpose= np.arange(12).reshape(3,4) 
transpose.T # the shape has changed to 4,3

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [35]:
#you can use np.dot function to perform matrix computations. You can calculate X transpose X as follows:
np.dot(transpose.T, transpose)

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

#Universal functions
They perform element wise operations on data in arrays.

In [36]:
funky=np.arange(8)
print(np.sqrt(funky))
print(np.exp(funky)) #exponent of the array
# these are called as unary functions

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]


In [37]:
# Binary functions take two value, Others such as maximum, add
x = random.randn(10)*10
y = random.randn(10)*10
print(x)
print(y)
print(np.maximum(x,y))# element wise operation
print(np.modf(x))# function modf returns the fractional and integral parts of a floating point arrays

[-20.87565713   8.26955861  -5.86236071   6.17257588  -9.23767676
   7.02380401   4.355988     7.60407023  19.30795122   5.17352394]
[ -8.56856303  -2.21958249   1.75379632   5.78494481  -4.96393866
  -3.47316227   1.56579766  -2.23648808 -13.15024494  -8.99216721]
[-8.56856303  8.26955861  1.75379632  6.17257588 -4.96393866  7.02380401
  4.355988    7.60407023 19.30795122  5.17352394]
(array([-0.87565713,  0.26955861, -0.86236071,  0.17257588, -0.23767676,
        0.02380401,  0.355988  ,  0.60407023,  0.30795122,  0.17352394]), array([-20.,   8.,  -5.,   6.,  -9.,   7.,   4.,   7.,  19.,   5.]))


#Data processing using Arrays

In [ ]:
mtrices =np.arange(-5,5,1)
print(mtrices)
x, y = np.meshgrid(mtrices, mtrices) #mesh grid function takes two 1 d arrays and produces two 2d arrays
print("Matrix values of y: {}".format(y))
print("Matrix values of x: {}".format(x))

[zip](http://stackoverflow.com/questions/13704860/zip-lists-in-python) function is clearly explained here.

In [ ]:
x1= np.array([1,2,3,4,5])
y1 = np.array([6,7,8,9,10])
cond =[True, False, True, True, False]
#If you want to take a value from x1 whenever the corresponding value in cond is true, otherwise take value from y.
z1 = [(x,y,z) for x,y,z in zip(x1, y1, cond)] # I have used zip function To illustrate the concept
print(z1)
np.where(cond, x1, y1) 

In [ ]:
from IPython.display import Image  
l = Image(filename='zipFunc.jpg')
l

In [ ]:
ra = np.random.randn(5,5)
# If you want to replace negative values in ra with -1 and positive values with 1. You can do it using where function
print(ra)
print(np.where(ra>0, 1, -1)) # If values in ra are greater than zero, replace it with 1, else replace it with -1.
# to set only positive values
np.where(ra >0, 1, ra) # same implies to negative values

# Statistical methods

In [40]:
thie = np.random.randn(5,5)
print(thie)
print(thie.mean()) # calculates the mean of thie
print(np.mean(thie)) # alternate method to calculate mean
print(thie.sum())

[[ 1.19332702 -0.36356714 -0.25743188 -0.59816572 -1.74873649]
 [-0.58442376 -0.78703362 -1.65622334  1.23221368  0.26079119]
 [ 0.69009307 -0.23096288 -1.53441764  0.41533491 -0.2170163 ]
 [ 0.09306437 -2.36785351 -1.17219257  1.5342651   0.14406613]
 [ 2.16847523 -0.77366198  0.79140696 -1.02799845  0.58758126]]
-0.16836265369184253
-0.16836265369184253
-4.2090663422960635


In [41]:
jp =np.arange(12).reshape(4,3)
print("The arrays are: {}".format(jp))
print("The sum of rows are :{}".format(np.sum(jp, axis =0))) #axis =0, gives you sum of the columns. axis =1 , gives sum of rows.
# remember this zero is for columns and one is for rows.

The arrays are: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The sum of rows are :[18 22 26]


In [43]:
jp =np.arange(12).reshape(4,3)
print("The arrays are: {}".format(jp))
print("The sum of rows are :{}".format(np.sum(jp, axis =1))) #axis =0, gives you sum of the columns. axis =1 , gives sum of rows.
# remember this zero is for columns and one is for rows.

The arrays are: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The sum of rows are :[ 3 12 21 30]


In [42]:
print(jp.sum(1))#returns sum of rows

[ 3 12 21 30]


In [44]:
jp.cumsum(0)  #cumulative sum of columns, try the same for jp.cumprod(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]])

In [45]:
jp.cumsum(1)#cumulative sum of rows

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30]])

In [ ]:
xp =np.random.randn(100)
print(xp)
print((xp > 0).sum()) # sum of all positive values
print((xp < 0).sum())
tandf =np.array([True,False,True,False,True,False])
print(tandf.any())#checks if any of the values are true
print(tandf.all()) #returns false even if a single value is false
#These methods also work with non-boolean arrays, where non-zero elements evaluate to True.

<b>Other array functions are:<br> </b>
std, var -> standard deviation and variance <br>
min, max -> Minimum and Maximum <br>
argmin, argmax -> Indices of minimum and maximum elements

#Sorting

In [ ]:
lp = np.random.randn(8)
print(lp)
lp.sort()
lp

In [ ]:
tp = np.random.randn(4,4)
tp

In [ ]:
tp.sort(1) #check the rows are sorted
tp

In [ ]:
personals = np.array(['Manu', 'Jeevan', 'Prakash', 'Manu', 'Prakash', 'Jeevan', 'Prakash'])
np.unique(personals)# returns the unique elements in the array

In [ ]:
set(personals) # set is an alternative to unique function

<b> Other Functions are :<br> </b>
intersect1d(x, y)-> Compute the sorted, common elements in x and y <br>
union1d(x,y) -> compute the sorted union of elements <br>
setdiff1d(x,y) -> set difference, elements in x that are not in y <br>
setxor1d(x, y) -> Set symmetric differences; elements that are in either of the arrays, but not both <br>

#Linear Algebra

In [ ]:
cp = np.array([[1,2,3],[4,5,6]])
dp = np.array([[7,8],[9,10],[11,12]])
print("CP array :{}".format(cp))
print("DP array :{}".format(dp))

In [ ]:
# element wise multiplication
cp.dot(dp) # this is equivalent to np.dot(x,y)

In [ ]:
np.dot(cp, np.ones(3)) 

In [ ]:
# numpy.linalg has standard matrix operations like determinants and inverse.
from numpy.linalg import inv, qr
cp = np.array([[1,2,3],[4,5,6]])
new_mat = cp.T.dot(cp) # multiply cp inverse and cp, this is element wise multiplication
new_mat

In [ ]:
sp = np.random.randn(5,5)
inv(sp)
rt = inv(sp)
rt

In [ ]:
# to calculate the product of a matrix and its inverse
sp.dot(rt)

In [ ]:
q,r = qr(sp)
print(q)
r

<b>Other Matrix Functions</b> <br>
<li>diag : Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square<br>
matrix with zeros on the off-diagonal
<li> trace: Compute the sum of the diagonal elements
<li> det: Compute the matrix determinant
<li> eig: Compute the eigenvalues and eigenvectors of a square matrix
<li> pinv: Compute the pseudo-inverse of a square matrix
<li> svd: Compute the singular value decomposition (SVD)
<li> solve: Solve the linear system Ax = b for x, where A is a square matrix
<li> lstsq: Compute the least-squares solution to y = Xb